version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:example@mongo_db:27017/projelogg?authSource=admin
    networks:
      - projelogg_network

  db:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - projelogg_network

networks:
  projelogg_network:
    driver: bridge

volumes:
  mongo_data:
